# Generated by Django 3.2.9 on 2022-04-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtempdowntime',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Post.dbworkunits', to_field='unit_ref'),
        ),
        migrations.AlterField(
            model_name='dbtubetechoperations',
            name='unitref',
            field=models.ForeignKey(blank=True, db_column='unitref', null=True, on_delete=django.db.models.deletion.RESTRICT, to='Post.dbworkunits', to_field='unit_ref'),
        ),
    ]
