# Generated by Django 3.2.9 on 2022-04-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_dbworkunits_unit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbshift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
