# Generated by Django 3.2.9 on 2022-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_dbshift_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbshift',
            name='time_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
