# Generated by Django 3.2.9 on 2022-04-04 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_dbshift_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbshift',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
