# Generated by Django 3.2.9 on 2022-05-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_dbshift_id'),
        ('Post', '0007_alter_dbshift_time_date'),
    ]

    operations = [
    ]
